USE GESTAO_PEDIDO
GO

IF OBJECTPROPERTY(object_id('dbo.SPD_PRODUTO'), N'IsProcedure') = 1
BEGIN
	DROP PROCEDURE dbo.SPD_PRODUTO
	PRINT '** A PROC SPD_PRODUTO FOI APAGADA COM SUCESSO **'
END
GO
CREATE PROCEDURE dbo.SPD_PRODUTO
(
	@ID_PRODUTO INT
)
AS
BEGIN
	SET NOCOUNT ON
----------------------

	DELETE TB_PRODUTO WHERE ID_PRODUTO = @ID_PRODUTO

----------------------
END
GO
IF OBJECTPROPERTY(object_id('dbo.SPD_PRODUTO'), N'IsProcedure') = 1
BEGIN
	PRINT '** A PROC SPD_PRODUTO FOI CRIADA COM SUCESSO **'
END
GO