USE GESTAO_PEDIDO
GO

IF OBJECTPROPERTY(object_id('dbo.SPD_PEDIDO'), N'IsProcedure') = 1
BEGIN
	DROP PROCEDURE dbo.SPD_PEDIDO
	PRINT '** A PROC SPD_PEDIDO FOI APAGADA COM SUCESSO **'
END
GO
CREATE PROCEDURE dbo.SPD_PEDIDO
(
	@ID_PEDIDO_PRODUTO INT
)
AS
BEGIN
	SET NOCOUNT ON
----------------------

	DECLARE @ID_PEDIDO INT

	SELECT @ID_PEDIDO = ID_PEDIDO 
	  FROM TB_PRODUTO_PEDIDO 
	 WHERE ID_PEDIDO_PRODUTO = @ID_PEDIDO_PRODUTO

	DELETE TB_PRODUTO_PEDIDO WHERE ID_PEDIDO_PRODUTO = @ID_PEDIDO_PRODUTO

	DELETE TB_PEDIDO WHERE ID_PEDIDO = @ID_PEDIDO

----------------------
END
GO
IF OBJECTPROPERTY(object_id('dbo.SPD_PEDIDO'), N'IsProcedure') = 1
BEGIN
	PRINT '** A PROC SPD_PEDIDO FOI CRIADA COM SUCESSO **'
END
GO