USE GESTAO_PEDIDO
GO

IF OBJECTPROPERTY(object_id('dbo.SPI_PEDIDO'), N'IsProcedure') = 1
BEGIN
	DROP PROCEDURE dbo.SPI_PEDIDO
	PRINT '** A PROC SPI_PEDIDO FOI APAGADA COM SUCESSO **'
END
GO
CREATE PROCEDURE dbo.SPI_PEDIDO
(
	@NM_CLIENTE VARCHAR(100),
	@DC_CIDADE VARCHAR(100),
	@DC_ESTADO VARCHAR(50),
	@NR_CEP INT,
	@DC_ENDERECO VARCHAR (100),
	@ID_PRODUTO INT,
	@NR_QUANTIDADE INT
)
AS
BEGIN
	SET NOCOUNT ON
----------------------

	DECLARE @ID_PEDIDO INT

	INSERT INTO TB_PEDIDO
				(
				  NM_CLIENTE,
				  DT_DATA_PEDIDO,
				  DC_CIDADE,
				  DC_ESTADO,
				  NR_CEP,
				  DC_ENDERECO,
				  DT_ALTERACAO
				)
		 VALUES (
				  @NM_CLIENTE,
				  GETDATE(),
				  @DC_CIDADE,
				  @DC_ESTADO,
				  @NR_CEP,
				  @DC_ENDERECO,
				  GETDATE()
				)

	SET @ID_PEDIDO = @@IDENTITY


	INSERT INTO TB_PRODUTO_PEDIDO
			   (
				 ID_PEDIDO,
				 ID_PRODUTO,
			 	 NR_QUANTIDADE
			   )
		VALUES (
				 @ID_PEDIDO,
				 @ID_PRODUTO,
				 @NR_QUANTIDADE
			   )

----------------------
END
GO
IF OBJECTPROPERTY(object_id('dbo.SPI_PEDIDO'), N'IsProcedure') = 1
BEGIN
	PRINT '** A PROC SPI_PEDIDO FOI CRIADA COM SUCESSO **'
END
GO