USE GESTAO_PEDIDO
GO

IF OBJECTPROPERTY(object_id('dbo.SPI_PRODUTO'), N'IsProcedure') = 1
BEGIN
	DROP PROCEDURE dbo.SPI_PRODUTO
	PRINT '** A PROC SPI_PRODUTO FOI APAGADA COM SUCESSO **'
END
GO
CREATE PROCEDURE dbo.SPI_PRODUTO
(
	@DC_PRODUTO VARCHAR(200),
	@DC_MARCA VARCHAR(100),
	@DC_CATEGORIA VARCHAR(100),
	@DC_UNIDADE_MEDIDA VARCHAR(10) = NULL,
	@VL_PRECO FLOAT = NULL
)
AS
BEGIN
	SET NOCOUNT ON
----------------------

	INSERT INTO TB_PRODUTO 
				(
				  DC_PRODUTO,
				  DC_MARCA,
				  DC_CATEGORIA,
				  DC_UNIDADE_MEDIDA,
				  VL_PRECO,
				  DT_ALTERACAO
				)
		 VALUES (
				  @DC_PRODUTO,
				  @DC_MARCA,
				  @DC_CATEGORIA,
				  @DC_UNIDADE_MEDIDA,
				  @VL_PRECO,
				  GETDATE()
				)

----------------------
END
GO
IF OBJECTPROPERTY(object_id('dbo.SPI_PRODUTO'), N'IsProcedure') = 1
BEGIN
	PRINT '** A PROC SPI_PRODUTO FOI CRIADA COM SUCESSO **'
END
GO