USE GESTAO_PEDIDO
GO

IF OBJECTPROPERTY(object_id('dbo.SPS_PEDIDO'), N'IsProcedure') = 1
BEGIN
	DROP PROCEDURE dbo.SPS_PEDIDO
	PRINT '** A PROC SPS_PEDIDO FOI APAGADA COM SUCESSO **'
END
GO
CREATE PROCEDURE dbo.SPS_PEDIDO
(
	@NM_CLIENTE VARCHAR(100) = NULL,
	@DC_PRODUTO VARCHAR(200) = NULL,
	@DC_CIDADE VARCHAR(100) = NULL,
	@DC_ESTADO VARCHAR(50) = NULL,
	@NR_CEP INT = NULL
)
AS
BEGIN
	SET NOCOUNT ON
----------------------
	
	DECLARE @SQL VARCHAR(MAX)


	SET @SQL = 'SELECT C.NM_CLIENTE,
					   B.DC_PRODUTO,
					   C.DC_CIDADE,
					   C.DC_ESTADO,
					   C.NR_CEP,
					   C.DC_ENDERECO,
					   A.NR_QUANTIDADE,
					   B.DC_UNIDADE_MEDIDA,
					   C.DT_DATA_PEDIDO
	              FROM TB_PRODUTO_PEDIDO A
				  JOIN TB_PRODUTO B
				    ON A.ID_PRODUTO = B.ID_PRODUTO
				  JOIN TB_PEDIDO C
				    ON A.ID_PEDIDO = C.ID_PEDIDO
				 WHERE 1=1
				 '


	--ADICIONA O FILTRO SE A VARIAVEL NAO ESTIVER NULA
	IF (@NM_CLIENTE IS NOT NULL)
	BEGIN
		SET @SQL = @SQL + 'OR C.NM_CLIENTE LIKE (%'+@NM_CLIENTE+'%) '
	END

	IF (@DC_PRODUTO IS NOT NULL)
	BEGIN
		SET @SQL = @SQL + 'OR B.DC_PRODUTO LIKE (%'+@DC_PRODUTO+'%) '
	END

	IF (@DC_CIDADE IS NOT NULL)
	BEGIN
		SET @SQL = @SQL + 'OR C.DC_CIDADE LIKE (%'+@DC_CIDADE+'%) '
	END

	IF (@DC_ESTADO IS NOT NULL)
	BEGIN
		SET @SQL = @SQL + 'OR C.DC_ESTADO LIKE (%'+@DC_ESTADO+'%) '
	END

	IF (@NR_CEP IS NOT NULL)
	BEGIN
		SET @SQL = @SQL + 'OR C.NR_CEP LIKE (%'+@NR_CEP+'%) '
	END


	--EXECUTA A QUERY CRIADA DINAMCIAMENTE
	EXEC (@SQL)
----------------------
END
GO
IF OBJECTPROPERTY(object_id('dbo.SPS_PEDIDO'), N'IsProcedure') = 1
BEGIN
	PRINT '** A PROC SPS_PEDIDO FOI CRIADA COM SUCESSO **'
END
GO