USE GESTAO_PEDIDO
GO

IF OBJECTPROPERTY(object_id('dbo.SPS_PRODUTO'), N'IsProcedure') = 1
BEGIN
	DROP PROCEDURE dbo.SPS_PRODUTO
	PRINT '** A PROC SPS_PRODUTO FOI APAGADA COM SUCESSO **'
END
GO
CREATE PROCEDURE dbo.SPS_PRODUTO
(
	@ID_PRODUTO INT = NULL,
	@DC_PRODUTO VARCHAR(200) = NULL,
	@DC_MARCA VARCHAR(100) = NULL,
	@DC_CATEGORIA VARCHAR(100) = NULL,
	@DC_UNIDADE_MEDIDA VARCHAR(10) = NULL
)
AS
BEGIN
	SET NOCOUNT ON
----------------------
	
	DECLARE @SQL VARCHAR(MAX)


	SET @SQL = 'SELECT ID_PRODUTO,
					   DC_PRODUTO,
					   DC_MARCA,
					   DC_CATEGORIA,
					   DC_UNIDADE_MEDIDA,
					   VL_PRECO,
					   DT_ALTERACAO 
	              FROM TB_PRODUTO
				 WHERE 1=1
				 '


	--ADICIONA O FILTRO SE A VARIAVEL NAO ESTIVER NULA
	IF (@ID_PRODUTO IS NOT NULL)
	BEGIN
		SET @SQL = @SQL + 'AND ID_PRODUTO = '+CONVERT(VARCHAR,@ID_PRODUTO)+' '
	END

	IF (@DC_PRODUTO IS NOT NULL)
	BEGIN
		SET @SQL = @SQL + 'AND DC_PRODUTO LIKE (''%'+@DC_PRODUTO+'%'') '
	END

	IF (@DC_MARCA IS NOT NULL)
	BEGIN
		SET @SQL = @SQL + 'AND DC_MARCA LIKE (''%'+@DC_MARCA+'%'') '
	END

	IF (@DC_CATEGORIA IS NOT NULL)
	BEGIN
		SET @SQL = @SQL + 'AND DC_CATEGORIA LIKE (''%'+@DC_CATEGORIA+'%'') '
	END

	IF (@DC_UNIDADE_MEDIDA IS NOT NULL)
	BEGIN
		SET @SQL = @SQL + 'AND DC_UNIDADE_MEDIDA LIKE (''%'+@DC_UNIDADE_MEDIDA+'%'') '
	END

	--EXECUTA A QUERY CRIADA DINAMCIAMENTE
	EXEC (@SQL)
----------------------
END
GO
IF OBJECTPROPERTY(object_id('dbo.SPS_PRODUTO'), N'IsProcedure') = 1
BEGIN
	PRINT '** A PROC SPS_PRODUTO FOI CRIADA COM SUCESSO **'
END
GO