USE GESTAO_PEDIDO
GO

IF OBJECTPROPERTY(object_id('dbo.SPU_PEDIDO'), N'IsProcedure') = 1
BEGIN
	DROP PROCEDURE dbo.SPU_PEDIDO
	PRINT '** A PROC SPU_PEDIDO FOI APAGADA COM SUCESSO **'
END
GO
CREATE PROCEDURE dbo.SPU_PEDIDO
(
	@ID_PEDIDO_PRODUTO INT,
	@NM_CLIENTE VARCHAR(100),
	@DC_CIDADE VARCHAR(100),
	@DC_ESTADO VARCHAR(50),
	@NR_CEP INT,
	@DC_ENDERECO VARCHAR (100),
	@NR_QUANTIDADE INT
)
AS
BEGIN
	SET NOCOUNT ON
----------------------

	DECLARE @ID_PEDIDO INT

	SELECT @ID_PEDIDO = ID_PEDIDO 
	  FROM TB_PRODUTO_PEDIDO 
	 WHERE ID_PEDIDO_PRODUTO = @ID_PEDIDO_PRODUTO

	 UPDATE TB_PEDIDO SET NM_CLIENTE = @NM_CLIENTE,
						  DC_CIDADE = @DC_CIDADE,
						  DC_ESTADO = @DC_ESTADO,
						  NR_CEP = @NR_CEP,
						  DC_ENDERECO = @DC_ENDERECO,
						  DT_ALTERACAO = GETDATE()
	  WHERE ID_PEDIDO = @ID_PEDIDO

	UPDATE TB_PRODUTO_PEDIDO SET NR_QUANTIDADE = @NR_QUANTIDADE 
	 WHERE ID_PEDIDO_PRODUTO = @ID_PEDIDO_PRODUTO

----------------------
END
GO
IF OBJECTPROPERTY(object_id('dbo.SPU_PEDIDO'), N'IsProcedure') = 1
BEGIN
	PRINT '** A PROC SPU_PEDIDO FOI CRIADA COM SUCESSO **'
END
GO