USE GESTAO_PEDIDO
GO

IF OBJECTPROPERTY(object_id('dbo.SPU_PRODUTO'), N'IsProcedure') = 1
BEGIN
	DROP PROCEDURE dbo.SPU_PRODUTO
	PRINT '** A PROC SPU_PRODUTO FOI APAGADA COM SUCESSO **'
END
GO
CREATE PROCEDURE dbo.SPU_PRODUTO
(
	@ID_PRODUTO INT,
	@DC_PRODUTO VARCHAR(200),
	@DC_MARCA VARCHAR(100),
	@DC_CATEGORIA VARCHAR(100),
	@DC_UNIDADE_MEDIDA VARCHAR(10),
	@VL_PRECO FLOAT
)
AS
BEGIN
	SET NOCOUNT ON
----------------------


	UPDATE TB_PRODUTO SET DC_PRODUTO = @DC_PRODUTO,
						  DC_MARCA = @DC_MARCA,
						  DC_CATEGORIA = @DC_CATEGORIA,
						  DC_UNIDADE_MEDIDA = @DC_UNIDADE_MEDIDA,
						  VL_PRECO = @VL_PRECO,
						  DT_ALTERACAO = GETDATE()

	 WHERE ID_PRODUTO = @ID_PRODUTO

----------------------
END
GO
IF OBJECTPROPERTY(object_id('dbo.SPU_PRODUTO'), N'IsProcedure') = 1
BEGIN
	PRINT '** A PROC SPU_PRODUTO FOI CRIADA COM SUCESSO **'
END
GO